package com.fptgang.backend.service;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public interface StatService {

    /**
     * Get the daily number of orders.
     * Used to analyze order trends over time.
     * 📊 **Recommended Chart Type:** Line Chart / Bar Chart
     * - Line Chart: Best for visualizing trends over time.
     * - Bar Chart: Can be used to compare daily order counts.
     * 🔹 **Data format:** [{x: date, y: orderCount}]
     */
    List<Map<String, Object>> getDailyOrders();

    /**
     * Get the total daily revenue.
     * Helps track sales performance over time.
     * 📊 **Recommended Chart Type:** Line Chart / Area Chart
     * - Line Chart: Shows revenue trends over time.
     * - Area Chart: Helps visualize revenue accumulation.
     * 🔹 **Data format:** [{x: date, y: totalRevenue}]
     */
    List<Map<String, Object>> getDailyRevenue();

    /**
     * Get the total monthly revenue.
     * Useful for evaluating long-term business growth.
     * 📊 **Recommended Chart Type:** Line Chart / Column Chart
     * - Line Chart: Shows revenue trends over months.
     * - Column Chart: Useful for comparing monthly revenue.
     * 🔹 **Data format:** [{x: yyyy-MM, y: totalRevenue}]
     */
    List<Map<String, Object>> getMonthlyRevenue();

    /**
     * Get the number of new customers who registered daily.
     * Helps measure customer acquisition effectiveness.
     * 📊 **Recommended Chart Type:** Line Chart / Bar Chart
     * - Line Chart: Shows customer sign-up trends.
     * - Bar Chart: Can compare new customers per day.
     * 🔹 **Data format:** [{x: date, y: newCustomers}]
     */
    List<Map<String, Object>> getDailyNewCustomers();

    /**
     * Get the number of new customers who registered monthly.
     * Useful for tracking long-term customer growth.
     * 📊 **Recommended Chart Type:** Line Chart / Column Chart
     * - Line Chart: Shows customer growth trend.
     * - Column Chart: Better for monthly comparisons.
     * 🔹 **Data format:** [{x: yyyy-MM, y: newCustomers}]
     */
    List<Map<String, Object>> getMonthlyNewCustomers();

    /**
     * Get the top-selling brands within a specified date range.
     * Helps identify the most successful brands in sales.
     * 📊 **Recommended Chart Type:** Pie Chart / Bar Chart
     * - Pie Chart: Shows the share of each brand in total sales.
     * - Bar Chart: Useful for comparing top brands by sales volume
     * 🔹 **Data format:** [{brand: "Brand Name", purchases: totalPurchases}]
     */
    List<Map<String, Object>> getTopBrands(LocalDateTime startDate, LocalDateTime endDate, int limit);

    /**
     * Get the total revenue generated by each SKU within a given date range.
     * Helps in analyzing the performance of individual product variations.
     * 📊 **Recommended Chart Type:** Bar Chart / Column Chart
     * - Bar Chart: Compares the revenue of different SKUs.
     * - Column Chart: Useful for visualizing revenue distribution.
     * 🔹 **Data format:** [{skuName: "SKU Name", totalRevenue: revenueAmount}]
     */
    List<Map<String, Object>> getRevenueBySKU(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get the total revenue generated by each Blind Box type within a given date range.
     * Useful for tracking which Blind Boxes contribute the most to revenue.
     * 📊 **Recommended Chart Type:** Bar Chart / Pie Chart
     * - Bar Chart: Compares revenue across different Blind Boxes.
     * - Pie Chart: Shows the proportion of revenue from each Blind Box type.
     * 🔹 **Data format:** [{blindBoxName: "Blind Box Name", totalRevenue: revenueAmount}]
     */
    List<Map<String, Object>> getRevenueByBlindBox(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get the total revenue generated by each brand within a given date range.
     * Useful for evaluating brand performance in terms of sales.
     * 📊 **Recommended Chart Type:** Pie Chart / Bar Chart
     * - Pie Chart: Shows revenue share of different brands.
     * - Bar Chart: Allows for side-by-side comparison of brand performance.
     * 🔹 **Data format:** [{brandName: "Brand Name", totalRevenue: revenueAmount}]
     */
    List<Map<String, Object>> getRevenueByBrand(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get revenue trends over a time period (day, week, or month).
     * Helps visualize revenue growth over different time intervals.
     * 📊 **Recommended Chart Type:** Line Chart / Area Chart
     * - Line Chart: Best for showing revenue trends over time.
     * - Area Chart: Helps visualize revenue accumulation over periods.
     * 🔹 **Data format:** [{x: timePeriod, y: totalRevenue}]
     */
    List<Map<String, Object>> getRevenueTrend(LocalDateTime startDate, LocalDateTime endDate, String groupBy);

    /**
     * Get the top-selling SKUs within a specified date range.
     * Helps identify the most popular SKUs based on sales volume.
     * 📊 **Recommended Chart Type:** Bar Chart / Column Chart
     * - Bar Chart: Compare SKUs by total units sold.
     * - Column Chart: Useful for visualizing SKU performance.
     * 🔹 **Data format:** [{sku: "SKU Name", quantitySold: totalSold}]
     */
    List<Map<String, Object>> getTopSellingSKUs(LocalDateTime startDate, LocalDateTime endDate, int limit);
}
