package com.fptgang.backend.service;
import com.fptgang.backend.model.stats.StringBigDecimalDatapoint;
import com.fptgang.backend.model.stats.StringIntegerDatapoint;

import java.time.LocalDateTime;
import java.util.List;

public interface StatService {

    /**
     * Get the daily number of orders.
     * Used to analyze order trends over time.
     * 📊 **Recommended Chart Type:** Line Chart / Bar Chart
     * - Line Chart: Best for visualizing trends over time.
     * - Bar Chart: Can be used to compare daily order counts.
     * 🔹 **Data format:** [{x: date, y: orderCount}]
     */
    List<StringIntegerDatapoint> getDailyOrders();

    /**
     * Get the total daily revenue.
     * Helps track sales performance over time.
     * 📊 **Recommended Chart Type:** Line Chart / Area Chart
     * - Line Chart: Shows revenue trends over time.
     * - Area Chart: Helps visualize revenue accumulation.
     * 🔹 **Data format:** [{key: date, value: totalRevenue}]
     */
    List<StringBigDecimalDatapoint> getDailyRevenue();

    /**
     * Get the total monthly revenue.
     * Useful for evaluating long-term business growth.
     * 📊 **Recommended Chart Type:** Line Chart / Column Chart
     * - Line Chart: Shows revenue trends over months.
     * - Column Chart: Useful for comparing monthly revenue.
     * 🔹 **Data format:** [{key: yyyy-MM, value: totalRevenue}]
     */
    List<StringBigDecimalDatapoint> getMonthlyRevenue();

    /**
     * Get the total revenue generated by each SKU within a given date range.
     * Helps in analyzing the performance of individual product variations.
     * 📊 **Recommended Chart Type:** Bar Chart / Column Chart
     * - Bar Chart: Compares the revenue of different SKUs.
     * - Column Chart: Useful for visualizing revenue distribution.
     * 🔹 **Data format:** [{skuName: "SKU Name", totalRevenue: revenueAmount}]
     */
    List<StringBigDecimalDatapoint> getRevenueBySKU(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get the total revenue generated by each Blind Box type within a given date range.
     * Useful for tracking which Blind Boxes contribute the most to revenue.
     * 📊 **Recommended Chart Type:** Bar Chart / Pie Chart
     * - Bar Chart: Compares revenue across different Blind Boxes.
     * - Pie Chart: Shows the proportion of revenue from each Blind Box type.
     * 🔹 **Data format:** [{key: "Blind Box Name", value: revenueAmount}]
     */
    List<StringBigDecimalDatapoint> getRevenueByBlindBox(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get the total revenue generated by each brand within a given date range.
     * Useful for evaluating brand performance in terms of sales.
     * 📊 **Recommended Chart Type:** Pie Chart / Bar Chart
     * - Pie Chart: Shows revenue share of different brands.
     * - Bar Chart: Allows for side-by-side comparison of brand performance.
     * 🔹 **Data format:** [{brandName: "Brand Name", totalRevenue: revenueAmount}]
     */
    List<StringBigDecimalDatapoint> getRevenueByBrand(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Get the top-selling SKUs by number of orders within a specified date range.
     * Helps identify the most frequently ordered SKUs.
     * 📊 **Recommended Chart Type:** Bar Chart / Column Chart
     * - Bar Chart: Compare SKUs by total number of orders.
     * - Column Chart: Useful for visualizing SKU order frequency.
     * 🔹 **Data format:** [{key: "SKU Name", value: totalOrders}]
     */
    List<StringIntegerDatapoint> getTopSellingSKUs(LocalDateTime startDate, LocalDateTime endDate, int limit);
}
