openapi: 3.0.1
info:
  title: 8lind8box Platform API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    Pageable:
      $ref: 'param/pageable.yml#/Pageable'
    Filter:
      $ref: 'param/filter.yml#/Filter'
    Search:
      $ref: 'param/search.yml#/Search'

  schemas:
    RefreshTokenDto:
      $ref: "model/refresh-token.yml#/RefreshTokenDto"
    TransactionDto:
      $ref: "model/transaction.yml#/TransactionDto"
    OrderDetailDto:
      $ref: "model/order-detail.yml#/OrderDetailDto"
    NotificationDto:
      $ref: "model/notification.yml#/NotificationDto"
    BlindBoxDto:
      $ref: "model/blindbox.yml#/BlindBoxDto"
    PromotionCampaignDto:
      $ref: "model/promotional-campaign.yml#/PromotionalCampaignDto"
    VideoDto:
      $ref: "model/video.yml#/VideoDto"
    BrandDto:
      $ref: "model/brand.yml#/BrandDto"
    ImageDto:
      $ref: "model/image.yml#/ImageDto"
    OrderDto:
      $ref: "model/order.yml#/OrderDto"
    ToyDto:
      $ref: "model/toy.yml#/ToyDto"
    SetDto:
      $ref: "model/set.yml#/SetDto"
    SlotDto:
      $ref: "model/slot.yml#/SlotDto"
    StockKeepingUnitDto:
      $ref: "model/stock-keeping-unit.yml#/StockKeepingUnitDto"
paths:
  /auth/me:
    $ref: "path/auth/me.yml"
  /auth/login-with-google:
    $ref: "path/auth/login-with-google.yml"
  /auth/refresh-token:
    $ref: "path/auth/refresh-token.yml"
  /auth/login:
    $ref: "path/auth/login.yml"
  /auth/register:
    $ref: "path/auth/register.yml"
  /auth/logout:
    $ref: "path/auth/log-out.yml"
  /auth/forgot-password:
    $ref: "path/auth/forgot-password.yml"
  /auth/reset-password:
    $ref: "path/auth/reset-password.yml"
  /accounts:
    $ref: "path/account.yml"
  /accounts/{accountId}:
    $ref: "path/account-accountId.yml"
  /blind-boxes:
    $ref: "path/blindbox.yml"
  /blind-boxes/{blindBoxId}:
    $ref: "path/blindbox-blindboxId.yml"
  /brands:
    $ref: "path/brand.yml"
  /brands/{brandId}:
    $ref: "path/brand-brandId.yml"
  /orders:
    $ref: "path/order.yml"
  /orders/{orderId}:
    $ref: "path/order-orderId.yml"
  /transactions:
    $ref: "path/transaction.yml"
  /transactions/{transactionId}:
    $ref: "path/transaction-transactionId.yml"
  /sets:
    $ref: "path/set.yml"
  /sets/{setId}:
    $ref: "path/set-setId.yml"
  /videos:
    $ref: "path/video.yml"
  /videos/{videoId}:
    $ref: "path/video-videoId.yml"
  /images:
    $ref: "path/image.yml"
  /images/{imageId}:
    $ref: "path/image-imageId.yml"
  /notifications:
    $ref: "path/notification.yml"
  /notifications/{notificationId}:
    $ref: "path/notification-notificationId.yml"
  /order-details:
    $ref: "path/order-detail.yml"
  /order-details/{orderDetailId}:
    $ref: "path/order-detail-orderDetailId.yml"
  /promotional-campaigns:
    $ref: "path/promotional-campaign.yml"
  /promotional-campaigns/{campaignId}:
    $ref: "path/promotional-campaign-campaignId.yml"
  /toys:
    $ref: "path/toy.yml"
  /toys/{toyId}:
    $ref: "path/toy-toyId.yml"
  /skus:
    $ref: "path/sku.yml"
  /skus/{skuId}:
    $ref: "path/sku-skuId.yml"
  /slots:
    $ref: "path/slot.yml"
  /slots/{slotId}:
    $ref: "path/slot-slotId.yml"
