get:
  summary: Get a list of packages
  operationId: getPackages
  security:
    - bearerAuth: []
  parameters:
    - $ref: '../param/pageable.yml#/Pageable'
    - $ref: '../param/filter.yml#/Filter'
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../component/page.yml#/Page'
              - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '../model/package.yml#/PackageDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'

post:
  summary: Create a package
  operationId: createPackage
  security:
    - bearerAuth: []
  requestBody:
    description: Package to create
    required: true
    content:
      application/json:
        schema:
          $ref: '../model/package.yml#/PackageDto'
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            $ref: '../model/package.yml#/PackageDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'