get:
  summary: Get a product by productId
  operationId: getProductById
  security:
    - bearerAuth: []
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64  # Updated to int64 for consistency with the model
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            $ref: '../model/product.yml#/ProductDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'

put:
  summary: Update an existing product
  operationId: updateProduct
  security:
    - bearerAuth: []
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64  # Updated to int64 for consistency with the model
  requestBody:
    description: Product to update
    required: true
    content:
      application/json:
        schema:
          $ref: '../model/product.yml#/ProductDto'
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            $ref: '../model/product.yml#/ProductDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'

delete:
  summary: Delete an existing product
  operationId: deleteProduct
  security:
    - bearerAuth: []
  parameters:
    - name: productId
      in: path
      required: true
      schema:
        type: integer
        format: int64  # Updated to int64 for consistency with the model
  responses:
    '200':
      description: The operation was successful
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'