get:
  summary: Get a list of products
  operationId: getProducts
  security:
    - bearerAuth: []
  parameters:
    - $ref: '../param/pageable.yml#/Pageable'
    - $ref: '../param/filter.yml#/Filter'
    - $ref: '../param/search.yml#/Search'
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../component/page.yml#/Page'
              - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '../model/product.yml#/ProductDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'

post:
  summary: Create a product
  operationId: createProduct
  security:
    - bearerAuth: []
  requestBody:
    description: Product to create
    required: true
    content:
      application/json:
        schema:
          $ref: '../model/product.yml#/ProductDto'
  responses:
    '200':
      description: The operation was successful
      content:
        application/json:
          schema:
            $ref: '../model/product.yml#/ProductDto'
    '400':
      description: The operation failed
      content:
        application/json:
          schema:
            $ref: '../component/error.yml#/ErrorResponse'