PackageDto:
  type: object
  properties:
    packageId:
      type: integer
      format: int64
    name:
      type: string
    description:
      type: string
    quantity:
      type: integer
      format: int32
    price:
      type: number
      format: double
    isVisible:
      type: boolean
    blindBoxes:
      type: array
      items:
        $ref: "blindbox.yml#/BlindBoxDto"
    orderDetails:
      type: array
      items:
        $ref: "order-detail.yml#/OrderDetailDto"
