name: PR Test Files Checker and Labeler
on: [pull_request_target]

jobs:
  check-and-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "fptgang/SBA301_Freelancer"

      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            test:
              - test/**
              - 'package.json'
              - 'package-lock.json'

      - name: List changed test files
        if: steps.changed-files-yaml.outputs.test_any_changed == 'true'
        env:
          TEST_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.test_all_changed_files }}
        run: |
          echo "Test-related files have changed:"
          for file in ${TEST_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Check changes and assign reviewer
        if: steps.changed-files-yaml.outputs.test_any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Add reviewer
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['vidz231']
            });

            // Check for modifications
            const files = '${{ steps.changed-files-yaml.outputs.test_all_changed_files }}'.split(' ');
            const modifiedFiles = files.filter(file => 
              !file.endsWith('removed') && !file.endsWith('added')
            );

            if (modifiedFiles.length > 0) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: 'Modified test files detected. Pull request cannot be merged.',
                event: 'REJECT'
              });
            }

      - name: Label PR
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
